log:
  level: debug
  disable_sentry: true

db:
  url:  "postgres://postgres:postgres@db:5432/url_shortener?sslmode=disable"

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: url-shortener-svc
  service_port: 80
