version: '3.8'

services:
  url-shortener:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=url_shortener
      - APP_PORT=8000
      - KV_VIPER_FILE=./config/config.yaml
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config.yaml:/config/config.yaml
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/usr/local/bin/config/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - url-shortener

volumes:
  db_data:
